# --- UPSTREAMS ---
upstream dspace_ui_upstream {
    server 127.0.0.1:8081;
}

upstream dspace_api_upstream {
    server dspace:8080;
}

server {
    listen 80;
    server_name _ ;

    client_max_body_size 512M;
    large_client_header_buffers 4 32k;
    
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    
    # Ngrok любить прості з'єднання
    proxy_http_version 1.1;
    proxy_set_header Connection "close";

    location / {
        proxy_pass http://dspace_ui_upstream;
        
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $http_host;
        
        # Force HTTPS for Ngrok
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
    }

    location /server {
        proxy_pass http://dspace_api_upstream/server;
        
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $http_host;
        
        # Force HTTPS for Ngrok
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        
        proxy_cookie_path /server /;
    }
}
