ui:
  # UI (Angular) сервер слухає всередині контейнера завжди по HTTP
  ssl: false
  host: 0.0.0.0
  port: 8081
  nameSpace: /
  # Публічний URL для генерації посилань
  baseUrl: https://repo.fby.com.ua
  useProxies: true

rest:
  # Налаштування для БРАУЗЕРА (куди стукати за даними)
  ssl: true
  host: repo.fby.com.ua
  port: 443
  nameSpace: /server
  ssrBaseUrl: http://dspace:8080/server

themes:
  - name: dspace
    headTags:
      - tagName: link
        attributes:
          rel: icon
          href: assets/dspace/images/favicons/favicon.ico
          sizes: any
      - tagName: link
        attributes:
          rel: icon
          href: assets/dspace/images/favicons/favicon.svg
          type: image/svg+xml
      - tagName: link
        attributes:
          rel: manifest
          href: assets/dspace/images/favicons/manifest.webmanifest
